# Generated by Django 5.1.8 on 2025-04-23 17:19

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('zerver', '0697_empty_topic_name_for_dms_from_third_party_imports'),  # Указываем актуальную предыдущую миграцию
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='can_create_topics_group',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='+',
                to='zerver.usergroup'
            ),
        ),
    ]